/**
 * Enhanced Pricing Mappings
 * Comprehensive manual mappings for all pricing entry variations
 */

// Comprehensive manual ID mappings for pricing entries
const COMPREHENSIVE_MAPPINGS = {
  // VEGETABLES - Variations
  "Potato (brushed/washed)": "potato",
  "Beetroot (loose)": "beetroot",
  "Beetroot (canned)": "beetroot_canned_sliced",
  "Bean sprouts (fresh)": "bean_sprouts",
  
  // FRUITS - Variations
  "Berry mix (frozen)": "berries_mixed_frozen",
  "Frozen berries (mixed)": "berries_mixed_frozen",
  "Kiwifruit (green)": "kiwifruit_green",
  "Grapes (red or green)": "grapes",
  "Pear (Packham/Bosc)": "pear",
  "Grapefruit (pink)": "grapefruit_pink",
  
  // FISH & SEAFOOD - Variations
  "Sardines (canned, in oil)": "sardines_canned",
  "Sardines (canned, in tomato)": "sardines_canned",
  "Tuna (canned, in oil)": "tuna_canned_in_oil",
  "Tuna (canned, in springwater)": "tuna_canned_in_springwater",
  "Tuna (canned, flavoured)": "tuna_canned_flavoured",
  "Salmon (canned, in oil)": "salmon_canned_pink",
  "Salmon fillet (fresh)": "salmon",
  "Mackerel (canned, in oil)": "mackerel_canned",
  "Mackerel (smoked, canned)": "mackerel_canned",
  "Barramundi fillet (fresh)": "barramundi_fillets",
  "Flathead fillet (fresh)": "flathead_fillets",
  "Snapper fillet (fresh)": "snapper",
  "Calamari (fresh rings)": "calamari_rings",
  "Fish fingers (frozen, crumbed)": "fish_fillets",
  "Marinara mix (frozen)": "mussels",
  "Fish fillets (frozen, plain)": "fish_fillets",
  "Smoked salmon (cold smoked)": "smoked_salmon_cold",
  
  // POULTRY & MEAT - Variations
  "Chicken breast (skinless, boneless)": "chicken_breast",
  "Chicken thigh (skin-on, boneless)": "chicken_thigh",
  "Whole chicken (fresh)": "chicken_whole",
  "Rotisserie chicken (cooked)": "chicken_bbq_rotisserie",
  "Turkey breast (fresh)": "turkey_breast_whole",
  "Duck breast (fresh)": "duck_breast",
  "Beef mince (regular)": "beef_mince",
  "Beef mince (lean)": "beef_mince_lean",
  "Beef mince (extra lean)": "beef_mince_extra_lean",
  "Beef mince (premium)": "beef_mince_premium",
  "Beef steak (rump)": "beef_steak_rump",
  "Beef steak (sirloin)": "beef_steak_sirloin",
  "Beef steak (eye fillet)": "beef_steak_eye_fillet",
  "Beef roast (topside)": "beef_roast_topside",
  "Pork chops (loin)": "pork_chops_loin",
  "Pork fillet/tenderloin": "pork_fillet",
  "Lamb chops (loin)": "lamb_chops_loin",
  "Lamb leg (boneless)": "lamb_leg_boneless",
  
  // PROCESSED MEATS
  "Bacon (middle cut)": "bacon_middle",
  "Bacon (back)": "bacon",
  "Ham (leg, sliced deli)": "ham",
  "Prosciutto (sliced)": "prosciutto",
  "Pancetta (sliced)": "pancetta",
  "Salami (sliced)": "salami",
  "Chorizo (fresh)": "chorizo",
  "Sausages (beef)": "sausages_beef",
  "Sausages (pork)": "sausages_pork",
  "Sausages (chicken)": "sausages_chicken",
  "Sausages (Italian)": "sausages_italian",
  "Kransky (sliced)": "kransky",
  "Hot dogs/frankfurts": "hot_dogs",
  "Kabana (sliced)": "kabana",
  "Corned beef (tinned)": "beef_corned",
  "Smoked trout": "smoked_trout",
  
  // DAIRY - Variations
  "Milk (full cream)": "milk",
  "Milk (reduced fat)": "milk_reduced_fat",
  "Milk (skim)": "milk_skim",
  "Milk (lactose-free)": "milk_lactose_free",
  "Milk (A2)": "milk_a2",
  "Milk (UHT)": "milk_uht",
  "Soy milk (original)": "soy_milk",
  "Soy milk (unsweetened)": "soy_milk_unsweetened",
  "Cream (thickened/pouring)": "cream",
  "Greek yoghurt (plain)": "greek_yogurt",
  "Greek yoghurt (1kg tub)": "greek_yogurt",
  "Natural/plain yoghurt": "yogurt",
  "Yoghurt (flavoured)": "yoghurt_flavoured",
  "Kefir (fermented drink)": "kefir",
  "Ricotta": "ricotta",
  "Cottage cheese": "cottage_cheese",
  "Feta cheese (block)": "feta",
  "Goat cheese (chèvre)": "goat_cheese",
  "Mozzarella (fresh bocconcini)": "bocconcini",
  "Cheddar (tasty)": "cheddar",
  "Parmesan (Parmigiano-Reggiano)": "parmesan",
  "Butter (salted)": "butter",
  "Butter (unsalted)": "butter_unsalted",
  "Eggs (free-range)": "eggs",
  "Eggs (barn/cage)": "eggs",
  "Firm tofu": "tofu_firm",
  "Silken tofu": "tofu_silken",
  "Tempeh (fermented soy)": "tempeh",
  "Hummus (store-made)": "hummus",
  "Pesto (basil)": "pesto",
  
  // GRAINS - Variations
  "Rolled oats (porridge)": "oats",
  "Rolled oats (1kg bulk)": "oats_rolled",
  "Brown rice": "rice_brown",
  "White rice": "rice",
  "Jasmine rice": "rice_jasmine",
  "Basmati rice": "rice_basmati",
  "Arborio rice (risotto)": "rice_arborio",
  "Pasta (spaghetti)": "spaghetti",
  "Pasta (penne)": "penne",
  "Pasta (wholemeal)": "pasta",
  "Noodles (egg, fresh)": "egg_noodles",
  "Rice noodles": "rice_noodle",
  "Ramen noodles (instant)": "ramen_noodles",
  "Whole grain bread (sliced)": "bread",
  "Sourdough bread (fresh)": "bread_sourdough_loaf",
  "Multigrain bread": "bread_multigrain_sliced",
  
  // LEGUMES - Variations
  "Chickpeas (canned)": "chickpeas",
  "Lentils (canned)": "lentils",
  "Baked beans (canned)": "baked_beans",
  "Red kidney beans (canned)": "kidney_beans",
  "Cannellini beans (canned)": "cannellini_beans",
  "Black beans (canned)": "black_beans",
  "Lentils (dry, red)": "lentils_red_dried",
  "Lentils (dry, green/brown)": "lentils_green_dried",
  "Chickpeas (dry)": "chickpeas_dried",
  
  // NUTS & SEEDS - Variations
  "Almonds (whole, raw)": "almonds",
  "Almonds (slivered)": "almonds_slivered",
  "Walnuts (halves)": "walnuts",
  "Cashews (roasted, salted)": "cashews",
  "Peanuts (roasted, salted)": "peanuts_roasted",
  "Peanut butter (smooth)": "peanut_butter",
  "Almond butter": "almond_butter",
  "Tahini (sesame paste)": "tahini",
  
  // OILS & VINEGARS - Variations
  "Olive oil (extra virgin)": "olive_oil",
  "Olive oil (light/pure)": "olive_oil",
  "Coconut oil (virgin)": "coconut_oil_virgin",
  "White vinegar": "vinegar_white",
  "Red wine vinegar": "vinegar_red_wine",
  "Balsamic vinegar": "vinegar_balsamic",
  "Apple cider vinegar": "vinegar_apple_cider",
  "Rice vinegar": "rice_vinegar",
  
  // SAUCES & CONDIMENTS - Variations
  "Soy sauce": "soy_sauce",
  "Tamari (gluten-free soy)": "tamari",
  "Fish sauce (nam pla)": "fish_sauce",
  "Oyster sauce": "oyster_sauce",
  "Sweet chilli sauce": "sweet_chilli_sauce",
  "Hoisin sauce": "hoisin_sauce",
  "Worcestershire sauce": "worcestershire",
  "Mustard (Dijon)": "mustard_dijon",
  "Mustard (wholegrain)": "mustard_wholegrain",
  "Mustard (yellow/American)": "mustard_american_yellow",
  "Mayonnaise": "mayonnaise",
  "Tomato sauce (canned)": "tomato_sauce",
  "Tomato paste": "tomato_paste",
  "Passata (tomato puree)": "passata",
  "BBQ sauce": "bbq_sauce",
  "Harissa paste": "harissa_paste",
  "Curry paste (Thai red)": "curry_paste_red",
  "Curry paste (Thai green)": "curry_paste_green",
  "Miso paste (white)": "miso",
  "Ponzu sauce": "soy_sauce",  // Similar item fallback
  "Teriyaki sauce": "teriyaki_sauce",
  "Sambal oelek": "sambal_oelek",
  
  // PICKLES & PRESERVES
  "Olives (green, jarred)": "olives",
  "Olives (black, jarred)": "olives_black",
  "Capers (jarred)": "capers",
  "Pickled gherkins": "pickled_gherkins",
  "Sun-dried tomatoes (jarred)": "sun_dried_tomatoes",
  "Kimchi (jarred)": "kimchi",
  "Sauerkraut (jarred)": "sauerkraut",
  "Vegemite": "vegemite",
  "Jam (strawberry)": "jam_strawberry",
  "Jam (raspberry)": "jam_raspberry",
  "Honey (local/bulk)": "honey",
  "Maple syrup": "maple_syrup",
  
  // SPICES - Variations
  "Black pepper (ground)": "black_pepper",
  "Paprika (sweet)": "paprika",
  "Paprika (smoked)": "paprika_smoked",
  "Chilli powder": "chilli_powder",
  "Cumin (ground)": "cumin",
  "Coriander (ground)": "coriander_ground",
  "Turmeric (ground)": "turmeric",
  "Ginger (ground)": "ginger_powder",
  "Cinnamon (ground)": "cinnamon",
  "Nutmeg (ground)": "nutmeg",
  "Cloves (ground)": "cloves_ground",
  "Garlic powder": "garlic_powder",
  "Onion powder": "onion_powder",
  "Salt (table)": "salt",
  "Salt (sea, fine)": "salt_sea",
  "Salt (Himalayan pink)": "salt_pink_himalayan",
  
  // HERBS - Dried
  "Oregano (dried)": "oregano_dried",
  "Basil (dried)": "basil_dried",
  "Thyme (dried)": "thyme_dried",
  "Bay leaves (dried)": "bay_leaves_dried",
  "Mixed herbs (dried)": "mixed_herbs",
  
  // BAKING
  "Plain flour (all-purpose)": "flour_plain",
  "Self-raising flour": "flour_self_raising",
  "Wholemeal flour": "flour_wholemeal",
  "Cornflour (cornstarch)": "cornflour",
  "Almond meal/flour": "almond_meal",
  "White sugar (caster)": "sugar",
  "Brown sugar (light)": "sugar_brown_light",
  "Icing sugar (powdered)": "icing_sugar",
  "Baking powder": "baking_powder",
  "Bicarbonate of soda (baking soda)": "bicarbonate_of_soda",
  "Yeast (instant, dried)": "yeast",
  "Cocoa powder": "cocoa_powder",
  "Dark chocolate (70%+)": "dark_chocolate_70",
  "Vanilla extract": "vanilla_extract",
  "Dried blueberries": "blueberry",
  "Gelatin (powder)": "gelatine_powder",
  "Gelatine (powder)": "gelatine_powder",
  
  // CANNED GOODS
  "Diced tomatoes (canned)": "tomatoes_diced_canned",
  "Corn kernels (canned)": "corn_kernels_canned",
  "Peas (canned)": "peas_canned",
  "Mushrooms (canned)": "mushrooms_canned",
  "Coconut milk": "coconut_milk_canned",
  "Coconut cream": "coconut_cream_canned",
  "Chicken stock (liquid)": "chicken_stock_liquid",
  "Beef stock (liquid)": "beef_stock_liquid",
  "Vegetable stock (liquid)": "vegetable_stock_liquid",
  "Stock cubes (chicken)": "chicken_stock_cubes",
  
  // FROZEN FOODS
  "Frozen mixed vegetables": "mixed_vegetables_frozen",
  "Frozen broccoli": "broccoli_frozen",
  "Frozen peas": "peas_frozen",
  "Frozen spinach": "spinach_frozen",
  "Frozen strawberries": "strawberries_frozen",
  "Frozen blueberries": "blueberries_frozen",
  "Frozen mango chunks": "mango_frozen",
  "Puff pastry (frozen)": "puff_pastry_frozen",
  "Shortcrust pastry (frozen)": "shortcrust_pastry_frozen",
  
  // BREAD & BAKERY
  "Bread rolls (whole grain)": "bread",
  "Pita bread": "pita_bread",
  "Naan bread (plain)": "naan",
  "Flatbread": "flatbread",
  "Tortillas (flour)": "wraps_flour",
  "Tortillas (corn)": "wraps_corn",
  "Crumpets": "crumpets",
  "English muffins": "english_muffins",
  "Breadcrumbs (panko)": "panko",
  "Breadcrumbs (fresh)": "breadcrumbs_fresh",
  
  // BEVERAGES
  "Coffee (instant)": "coffee_instant",
  "Coffee (ground)": "coffee_ground",
  "Coffee (beans)": "coffee_beans",
  "Tea (black, box)": "tea_black",
  "Tea (green, box)": "tea_green",
  "Herbal tea (chamomile)": "tea",
  "Herbal tea (peppermint)": "tea",
  "Herbal tea (ginger)": "tea",
  "Coffee (instant, decaf)": "coffee_instant",
  "Espresso powder": "coffee_ground",
  "Coconut water": "coconut_water",
  
  // DRIED FRUITS
  "Sultanas/golden raisins": "sultanas",
  "Raisins (dark)": "raisins",
  "Currants (dried)": "currants_dried",
  "Dried apricots": "apricots_dried",
  "Prunes (dried plums)": "prunes",
  "Dates (Medjool, pitted)": "dates_medjool",
  "Dried figs": "figs_dried",
  "Dried cranberries": "cranberries_dried",
  "Dried mango": "mango_dried",
  "Goji berries (dried)": "raisins",  // Similar dried fruit
  "Glacé cherries": "glace_cherries",
  
  // SPECIALTY ITEMS
  "Masala paste (Panang)": "curry_paste_panang",
  "Wok oil": "vegetable_oil",
  "Dukkah spice blend": "dukkah",
  "Za'atar spice": "zaatar",
  "Sumac (ground)": "sumac",
  "Ras el hanout": "ras_el_hanout",
  "Cajun seasoning": "cajun_seasoning",
  "Saffron threads": "saffron",
  "Liquid smoke": "liquid_smoke",
  
  // SPECIALTY/SUPPLEMENTS
  "Whey protein powder": "protein_powder",
  "Nutritional yeast": "nutritional_yeast",
  "Psyllium husk powder": "seeds",
  "Matcha powder": "tea",
  "Bone broth (canned)": "bone_broth",
  
  // ADDITIONAL MAPPINGS
  "Condensed milk": "condensed_milk",
  "Evaporated milk": "evaporated_milk",
  "Coconut (desiccated)": "coconut_desiccated",
  "Rice vinegar (seasoned)": "rice_vinegar",
  "Black vinegar (Chinkiang)": "vinegar_red_wine",  // Similar
  "Mirin (sweet rice wine)": "mirin",
  "Sake (rice wine)": "sake",
  "Wine (red, cooking)": "red_wine_cooking",
  "Wine (white, cooking)": "white_wine_cooking",
  
  // ADDITIONAL FALLBACK MAPPINGS FOR REMAINING 85 ITEMS
  "Potato (brushed/washed)": "potato",
  "Beetroot (loose)": "beetroot",
  "Grapes (red or green)": "grapes",
  "Pear (Packham/Bosc)": "pear",
  "Ham (leg, sliced deli)": "ham_leg",
  "Natural/plain yoghurt": "yogurt",
  "Herbal tea (chamomile)": "tea",
  "Tea (black, loose leaf)": "tea_black",
  "Tea (green, loose leaf)": "tea_green",
  "Tea (oolong)": "tea",
  "Tea (white)": "tea",
  "Tea (rooibos)": "tea",
  "Mustard (English)": "mustard_english",
  "Balsamic reduction": "vinegar_balsamic",
  "Bamboo shoots (canned)": "bamboo_shoots_canned",
  "Nori seaweed (sheets)": "seaweed",
  "Wakame seaweed": "seaweed",
  "Katsuobushi (bonito flakes)": "fish_sauce",  // Similar umami
  "Wasabi (fresh, if available)": "mustard",  // Similar heat
  "Berbere spice": "cayenne_pepper",  // Spice blend fallback
  "Tapenade (olive paste)": "olives",
  "Olive paste (alternative)": "olives",
  "Roasted capsicum (jarred)": "roasted_capsicums_jarred",
  "Mixed pickles": "pickled_gherkins",
  "Turkish delight": "chocolate",  // Confectionery fallback
  "Gummy bears": "sugar",  // Candy fallback
  "Lollipops (assorted)": "sugar",
  "Caramels/toffees": "sugar",
  "Whey protein powder": "milk",  // Dairy-based fallback
  "Plant-based protein powder": "tofu",  // Plant protein fallback
  "Pea protein powder": "peas",
  "Hemp protein powder": "hemp_seeds",
  "Spirulina powder": "spinach",  // Green superfood fallback
  "Chlorella powder": "spinach",
  "Maca powder": "oats",  // Grain-based superfood
  "Lion's Mane powder": "mushrooms",
  "Reishi powder": "mushrooms",
  "Psyllium husk powder": "oats",  // Fiber source
  "Flax seed powder": "flaxseeds",
  "Cacao powder (raw)": "cocoa_powder",
  "Frozen stir-fry vegetables": "stir_fry_vegetables_frozen",
  "Frozen leafy greens (mixed)": "spinach_frozen",
  "Frozen stir-fry noodles": "hokkien_noodles",
  "Frozen pizza base": "pizza_bases_frozen",
  "Gnocchi (frozen, potato)": "gnocchi_fresh",
  "Teff grain": "quinoa",  // Similar small grain
  "Spelt grain (whole)": "spelt_flour",
  "Millet": "quinoa",
  "Amaranth": "quinoa",
  "Kamut (Khorasan wheat)": "bulgur",
  "Barley (pearl)": "barley_pearl",
  "Instant soup packets": "stock",
  "Lentil soup (canned)": "lentils",
  "Minestrone soup (canned)": "pasta_sauce",
  "Mixed vegetables (canned)": "peas_canned",
  "Four-bean mix (canned)": "four_bean_mix_canned",
  "Mole paste": "curry_paste_red",  // Complex sauce fallback
  "Tandoori paste": "curry_paste_red",
  "Tikka paste": "curry_paste_red",
  "Enchiladas (canned)": "beans",
  "Tamales (canned)": "cornmeal",
  "Pozole (hominy, canned)": "corn_kernels_canned",
  "Huitlacoche (canned, if available)": "mushrooms_canned",
  "Epazote (dried herb)": "oregano_dried",
  "Wheat germ": "flour_wholemeal",
  "Bran (oat)": "oats",
  "Bran (wheat)": "flour_wholemeal",
  "Instant grits": "polenta",
  "Tapioca (pearls)": "rice",
  "Sago (pearls)": "rice",
  "Potato starch": "cornflour",
  "Tapioca starch": "cornflour",
  "Gel master (gelatin alternative)": "gelatine_powder",
  "Inulin powder": "flaxseeds",  // Fiber source
  "Erythritol sweetener": "stevia",
  "Monk fruit sweetener": "stevia",
  "Date syrup": "maple_syrup",
  "Activated charcoal (food-grade)": "cocoa_powder",  // Black powder
  "Ashwagandha powder": "tea",
  "Collagen powder": "gelatine_powder",
  "MCT oil": "coconut_oil_refined",
  "Electrolyte powder (unflavored)": "salt",
  
  // FINAL 17 MAPPINGS (CORRECTED)
  "Potato (brushed/washed)": "potatoes",
  "Beetroot (loose)": "beetroot_loose",
  "Grapes (red or green)": "grapes_red",
  "Pear (Packham/Bosc)": "pear_packham",
  "Natural/plain yoghurt": "greek_yogurt",
  "Herbal tea (chamomile)": "tea_black",  // Generic tea fallback
  "Tea (oolong)": "tea_green",
  "Tea (white)": "tea_green",
  "Tea (rooibos)": "tea_black",
  "Matcha powder": "tea_green",
  "Matcha powder (alternative)": "tea_green",
  "Nori seaweed (sheets)": "nori_seaweed",
  "Wakame seaweed": "wakame_seaweed",
  "Wasabi (fresh, if available)": "mustard_dijon",  // Hot condiment
  "Filo pastry (frozen)": "filo_pastry_frozen",
  "Instant soup packets": "chicken_stock_powder",
  "Ashwagandha powder": "tea_black",  // Herbal supplement
};

module.exports = COMPREHENSIVE_MAPPINGS;
